update_config:
  enabled: true
  update_branch_format: version-update/{0}
  labels:
    - version-update
  pr_reviewers:
    - folio-org/kitfox
    - folio-org/erm

branches:
  - snapshot:
      enabled: false
      need_pr: false
#  - R2-2024:
#      enable: false
#      need_pr: true
