name: Release update scheduler

run-name: Release update scheduler ${{ github.event_name == 'workflow_dispatch' && '[manual]' || '' }}

on:
  schedule:
    - cron: "*/20 * * * *"
  
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Perform dry run without creating PRs'
        required: false
        type: boolean
        default: false

concurrency:
  group: release-scan-${{ github.repository }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  get-config:
    name: Get Configuration
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.get-config.outputs.branches }}
      branch_count: ${{ steps.get-config.outputs.branch_count }}
      pr_reviewers: ${{ steps.get-config.outputs.pr_reviewers }}
      pr_labels: ${{ steps.get-config.outputs.pr_labels }}
      branch_config: ${{ steps.get-config.outputs.branch_config }}
    steps:         
      - name: Get Release Configuration
        id: get-config
        uses: folio-org/kitfox-github/.github/actions/get-update-config@master
        with:
          repo: ${{ github.repository }}
          github_token: ${{ github.token }}
      

  update-branches:
    name: Update ${{ matrix.branch }}
    needs: get-config
    if: needs.get-config.outputs.branch_count > 0
    strategy:
      matrix:
        include: ${{ fromJson(needs.get-config.outputs.branch_config) }}
      fail-fast: false
      max-parallel: 3
    uses: folio-org/kitfox-github/.github/workflows/release-update.yml@master
    with:
      release_branch: ${{ matrix.branch }}
      update_branch: ${{ matrix.update_branch }}
      dry_run: ${{ github.event_name == 'workflow_dispatch' && inputs.dry_run || false }}
      pr_reviewers: ${{ needs.get-config.outputs.pr_reviewers }}
      pr_labels: ${{ needs.get-config.outputs.pr_labels }}
    secrets: inherit
